(define (http-get url . options)
  (let ((easy (curl:easy-init)))
    (curl:setopt easy "CURLOPT_URL" url)
    (for-each (lambda (i)
	       (curl:setopt easy (car i) (cdr i)))
	     options)
    (curl:perform easy)
    (curl:cleanup easy)))
